dist: xenial
sudo: false
language: csharp
dotnet: 5.0.103
mono: none
script:
  - git fetch --unshallow # in order to make Nerdbank.GitVersioning.Tasks.GetBuildVersion work
  - dotnet restore ./GroBuf.sln --verbosity m
  - dotnet build --configuration Release --framework netstandard2.0 ./GroBuf/GroBuf.csproj
  - dotnet build --configuration Release --framework net5.0 ./GroBuf.Tests/GroBuf.Tests.csproj
  - dotnet test --no-build --configuration Release --framework net5.0 --filter TestCategory!=LongRunning ./GroBuf.Tests/GroBuf.Tests.csproj
