version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
branches:
  only:
    - master
build_script:
- ps: '& { ./build.ps1 -Script build.cake -Target Build-And-Merge -Configuration Release }'
after_build:
- nuget pack GroBuf.nuspec
- appveyor PushArtifact GroBuf.*.nupkg
