image: Visual Studio 2017

init:
  - cmd: git config --global core.autocrlf false

before_build:
  - cmd: dotnet --info
  - cmd: dotnet restore ./GroBuf.sln --verbosity m

build_script:
  - cmd: dotnet build --configuration Release ./GroBuf.sln

test_script:
  - cmd: dotnet test --no-build --configuration Release --filter TestCategory!=LongRunning ./GroBuf.Tests/GroBuf.Tests.csproj
